User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - control'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - control'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaacf'
> conda --version
> conda info --json
> pyenv root
> python3.7 ~/.vscode-oss/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode-oss/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode-oss/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode-oss/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-oss/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-oss/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Error 2020-09-09 15:01:28: Failed to download and store experiments, Class name = b, completed in 1695ms, has a falsy return value, , Return Value: undefined [Error: Failed with status 404, Not Found, Uri https://raw.githubusercontent.com/microsoft/vscode-python/master/experiments.json
	at H._callback (/home/nice/.vscode-oss/extensions/ms-python.python-2020.8.106424/out/client/extension.js:54:713175)
	at H.a._callback.a.callback.a.callback (/home/nice/.vscode-oss/extensions/ms-python.python-2020.8.106424/out/client/node_modules/request.js:189:5442)
	at H.emit (events.js:203:13)
	at H.<anonymous> (/home/nice/.vscode-oss/extensions/ms-python.python-2020.8.106424/out/client/node_modules/request.js:189:18302)
	at H.emit (events.js:203:13)
	at IncomingMessage.<anonymous> (/home/nice/.vscode-oss/extensions/ms-python.python-2020.8.106424/out/client/node_modules/request.js:189:17134)
	at Object.onceWrapper (events.js:291:20)
	at IncomingMessage.emit (events.js:208:15)
	at endReadableNT (_stream_readable.js:1168:12)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)]
Error 2020-09-09 15:01:28: Failed to initialize experiments, Class name = b, completed in 1704ms, has a falsy return value, , Return Value: undefined [Error: Failed with status 404, Not Found, Uri https://raw.githubusercontent.com/microsoft/vscode-python/master/experiments.json
	at H._callback (/home/nice/.vscode-oss/extensions/ms-python.python-2020.8.106424/out/client/extension.js:54:713175)
	at H.a._callback.a.callback.a.callback (/home/nice/.vscode-oss/extensions/ms-python.python-2020.8.106424/out/client/node_modules/request.js:189:5442)
	at H.emit (events.js:203:13)
	at H.<anonymous> (/home/nice/.vscode-oss/extensions/ms-python.python-2020.8.106424/out/client/node_modules/request.js:189:18302)
	at H.emit (events.js:203:13)
	at IncomingMessage.<anonymous> (/home/nice/.vscode-oss/extensions/ms-python.python-2020.8.106424/out/client/node_modules/request.js:189:17134)
	at Object.onceWrapper (events.js:291:20)
	at IncomingMessage.emit (events.js:208:15)
	at endReadableNT (_stream_readable.js:1168:12)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)]
> python ~/.vscode-oss/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-oss/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> pyenv root
> /usr/bin/python ~/.vscode-oss/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/bin/python ~/.vscode-oss/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/bin/python ~/.vscode-oss/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/bin/python ~/.vscode-oss/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
Error 2020-09-09 15:01:31: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/home/nice/.config/Code/User/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/nice/.config/Code/User/settings.json')
	at _handleError (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:672:249)
	at async v.readText (/home/nice/.vscode-oss/extensions/ms-python.python-2020.8.106424/out/client/extension.js:1:495817)
	at async p.doesFileNeedToBeFixed (/home/nice/.vscode-oss/extensions/ms-python.python-2020.8.106424/out/client/extension.js:56:953520)
	at async /home/nice/.vscode-oss/extensions/ms-python.python-2020.8.106424/out/client/extension.js:56:952647
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/nice/.vscode-oss/extensions/ms-python.python-2020.8.106424/out/client/extension.js:56:952593)
	at async p.updateTestSettings (/home/nice/.vscode-oss/extensions/ms-python.python-2020.8.106424/out/client/extension.js:56:952220)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Error 2020-09-09 15:01:31: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/home/nice/.config/.vscode/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/nice/.config/.vscode/settings.json')
	at _handleError (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:672:249)
	at async v.readText (/home/nice/.vscode-oss/extensions/ms-python.python-2020.8.106424/out/client/extension.js:1:495817)
	at async p.doesFileNeedToBeFixed (/home/nice/.vscode-oss/extensions/ms-python.python-2020.8.106424/out/client/extension.js:56:953520)
	at async /home/nice/.vscode-oss/extensions/ms-python.python-2020.8.106424/out/client/extension.js:56:952647
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/home/nice/.vscode-oss/extensions/ms-python.python-2020.8.106424/out/client/extension.js:56:952593)
	at async p.updateTestSettings (/home/nice/.vscode-oss/extensions/ms-python.python-2020.8.106424/out/client/extension.js:56:952220)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Starting Microsoft Python language server.
Python interpreter path: /usr/bin/python
> conda info --json
> conda --version
